In [1]:
from ast import literal_eval
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/kexinhuang/Downloads/TDC Leaderboard Submission Form 2.csv')

In [2]:
df = df.rename(columns = {
    df.columns.values[0]: 'Time',
    df.columns.values[1]: 'Name',
    df.columns.values[2]: 'Email',
    df.columns.values[3]: 'Group',
    df.columns.values[4]: 'Model',
    df.columns.values[5]: 'Paper_URL',
    df.columns.values[6]: 'Code_URL',
    df.columns.values[7]: 'Result',
    df.columns.values[8]: 'Hardware',
    df.columns.values[9]: '#Params'    
})
df = df.drop(df.columns.values[10], axis = 1)

In [3]:
df['Result'] = df.Result.apply(literal_eval)

In [4]:
metrics_direction = {
    'mae': 'desc',
    'roc-auc': 'asc', 
    'pr-auc': 'asc',
    'pcc': 'asc'
}

In [5]:
def retrieve_mean(x, categories):
    l = []
    for i in categories:
        l.append(x[i][0])
    return np.array(l)

## ADMET Group

In [6]:
df_admet = df[df.Group == 'ADMET Group']

In [7]:
admet_metrics = {'caco2_wang': 'mae',
            'hia_hou': 'roc-auc',
            'pgp_broccatelli': 'roc-auc', 
            'bioavailability_ma': 'roc-auc',
            'lipophilicity_astrazeneca': 'mae',
            'solubility_aqsoldb': 'mae',
            'bbb_martins': 'roc-auc',
            'ppbr_az': 'mae',
            'vdss_lombardo': 'pcc',
            'cyp2c9_veith': 'pr-auc',
            'cyp2d6_veith': 'pr-auc',
            'cyp3a4_veith': 'pr-auc',
            'cyp2c9_substrate_carbonmangels': 'pr-auc',
            'cyp3a4_substrate_carbonmangels': 'roc-auc',
            'cyp2d6_substrate_carbonmangels': 'pr-auc',
            'half_life_obach': 'pcc',
            'clearance_hepatocyte_az': 'pcc',
            'clearance_microsome_az': 'pcc',
            'ld50_zhu': 'mae',
            'herg': 'roc-auc',
            'ames': 'roc-auc',
            'dili': 'roc-auc'
            }

In [8]:
ADMET = {
    'Absorption': ['caco2_wang', 'hia_hou', 'pgp_broccatelli', 'bioavailability_ma', 'lipophilicity_astrazeneca', 'solubility_aqsoldb'],
    'Distribution': ['bbb_martins', 'ppbr_az', 'vdss_lombardo'],
    'Metabolism': ['cyp2c9_veith', 'cyp2d6_veith', 'cyp3a4_veith', 'cyp2c9_substrate_carbonmangels', 'cyp2d6_substrate_carbonmangels', 'cyp3a4_substrate_carbonmangels'],
    'Excretion': ['half_life_obach', 'clearance_hepatocyte_az', 'clearance_microsome_az'],
    'Toxicity': ['ld50_zhu', 'herg', 'ames', 'dili']
}

In [23]:
results = df_admet.Result.apply(lambda x: x['caco2_wang'][0]).values
out = np.argsort(results)
idx2rank = dict(zip(out, list(range(len(out)))))

idx2rank

{1: 0, 0: 1, 2: 2}

In [24]:
results

array([0.446, 0.393, 0.908])

In [31]:
def get_entries(bm):
    results = df_admet.Result.apply(lambda x: x[bm][0]).values
    print(results)
    
    '''
    rank_dict = dict(zip(range(results.shape[0]), list([0] * results.shape[0])))
    
    for idx, i in enumerate(range(results.T.shape[0])):
        # for every benchmark
        sort_idx = np.argsort(results.T[i], axis = 0)
        if metrics_direction[admet_metrics[ADMET[category][idx]]] == 'desc':
            sort_idx = np.argsort(results.T[i], axis = 0)
        else:
            sort_idx = np.argsort(results.T[i], axis = 0)[::-1]
        
        for pos, val in enumerate(sort_idx):
            rank_dict[val] = rank_dict[val] + pos
    
    rank = [] # [rank for 1, rank for 2, ...]
    for i in range(results.shape[0]):
        rank.append(rank_dict[i])
        
    out = np.argsort(rank)
    
    idx2rank = dict(zip(out, list(range(len(out)))))
    rank2idx = dict(zip(list(range(len(out))), out))
    '''
    out = np.argsort(results)
    idx2rank = dict(zip(out, list(range(len(out)))))
    rank2idx = dict(zip(list(range(len(out))), out))
    
    print('---- ' + bm + ' ------')
    print('---- ' + admet_metrics[bm] + ' ------')
    entries = []
    for submit_idx in range(len(df_admet)):
        temp = df_admet.iloc[submit_idx]
        html_code = '<tr> \n'
        html_code = html_code + '  <td> ' + str(idx2rank[submit_idx] + 1) + ' </td> \n'        
        html_code = html_code + '  <td> ' + temp.Model + ' </td> \n'
        html_code = html_code + '  <td><a href="mailto:' + temp.Email + '">' + temp.Name + '</a></td> \n'
        html_code = html_code + '  <td><a href="' + temp.Code_URL + '"> GitHub</a>, <a href="' + temp.Paper_URL + '">Paper </a></td> \n'
        value = temp['#Params']
        html_code = html_code + '  <td> ' + f'{value:,}' + ' </td> \n'
        html_code = html_code + '  <td>' + format(temp.Result[bm][0], '.3f') + ' <span>&#177;</span> ' + format(temp.Result[bm][1], '.3f') +' </td> \n'
        html_code += '</tr>'

        entries.append(html_code)
    
    for i in range(len(out)):
        print(entries[rank2idx[i]])

In [33]:
for i, j in ADMET.items():
    for x in j:
        get_entries(x)

[0.446 0.393 0.908]
---- caco2_wang ------
---- mae ------
<tr> 
  <td> 1 </td> 
  <td> RDKit2D + MLP (DeepPurpose) </td> 
  <td><a href="mailto:kexinhuang@hsph.harvard.edu">Kexin Huang</a></td> 
  <td><a href="https://github.com/mims-harvard/TDC/tree/master/examples/single_pred/admet"> GitHub</a>, <a href="https://doi.org/10.1093/bioinformatics/btaa1005">Paper </a></td> 
  <td> 633,409 </td> 
  <td>0.393 <span>&#177;</span> 0.024 </td> 
</tr>
<tr> 
  <td> 2 </td> 
  <td> CNN (DeepPurpose) </td> 
  <td><a href="mailto:kexinhuang@hsph.harvard.edu">Kexin Huang</a></td> 
  <td><a href="https://github.com/mims-harvard/TDC/tree/master/examples/single_pred/admet"> GitHub</a>, <a href="https://doi.org/10.1093/bioinformatics/btaa1005">Paper </a></td> 
  <td> 226,625 </td> 
  <td>0.446 <span>&#177;</span> 0.036 </td> 
</tr>
<tr> 
  <td> 3 </td> 
  <td> Morgan + MLP (DeepPurpose) </td> 
  <td><a href="mailto:kexinhuang@hsph.harvard.edu">Kexin Huang</a></td> 
  <td><a href="https://github.com/mim

## Docking Group

In [6]:
df_docking = df[df.Group == 'Docking Group']

In [7]:
df_docking

Time        Name             Email          Group  \
4  2021/05/18 10:04:18 PM MDT  Tianfan Fu  tfu42@gatech.edu  Docking Group   
5  2021/05/18 10:06:18 PM MDT  Tianfan Fu  tfu42@gatech.edu  Docking Group   
6  2021/05/18 10:13:31 PM MDT  Tianfan Fu  tfu42@gatech.edu  Docking Group   

         Model                                          Paper_URL  \
4         GCPN                   https://arxiv.org/abs/1806.02473   
5     Graph-GA  https://pubs.rsc.org/en/content/articlelanding...   
6  SMILES-LSTM  https://pubs.acs.org/doi/10.1021/acscentsci.7b...   

                                    Code_URL  \
4          https://github.com/futianfan/GCPN   
5  https://github.com/futianfan/guacamol_tdc   
6  https://github.com/futianfan/guacamol_tdc   

                                              Result Hardware  #Params  
4  {'DRD3': {100: {'top100': [3.86, 0.102], 'top1...      GPU    17600  
5  {'DRD3': {100: {'top100': [-7.222, 0.013], 'to...      GPU        0  
6  {'DRD3': {100: {'top100': [-7.594, 0.182], 'to...     GPUs  3149000

In [14]:
bm = 'DRD3'
max_calls = 100
results = df_docking.Result.apply(lambda x: x[bm][max_calls]['top100'][0]).values
np.argsort(results)

array([2, 1, 0])

In [19]:
def get_entries(bm, max_calls):
    results = df_docking.Result.apply(lambda x: x[bm][max_calls]['top100'][0]).values
    
    out = np.argsort(results)
    idx2rank = dict(zip(out, list(range(len(out)))))
    rank2idx = dict(zip(list(range(len(out))), out))
    
    print('---- ' + bm + ' ------')
    entries = []
    for submit_idx in range(len(df_docking)):
        temp = df_docking.iloc[submit_idx]
        html_code = '<tr> \n'
        html_code = html_code + '  <td> ' + str(idx2rank[submit_idx] + 1) + ' </td> \n'        
        html_code = html_code + '  <td> ' + temp.Model + ' </td> \n'
        html_code = html_code + '  <td><a href="mailto:' + temp.Email + '">' + temp.Name + '</a></td> \n'
        html_code = html_code + '  <td><a href="' + temp.Code_URL + '"> GitHub</a>, <a href="' + temp.Paper_URL + '">Paper </a></td> \n'
        value = temp['#Params']
        html_code = html_code + '  <td> ' + f'{value:,}' + ' </td> \n'
        for metric in ['top100', 'top10', 'top1', 'diversity', 'novelty', '%pass', 'top1_%pass', 'm1']:
            html_code = html_code + '  <td>' + format(temp.Result[bm][max_calls][metric][0], '.3f') + ' <span>&#177;</span> ' + format(temp.Result[bm][max_calls][metric][1], '.3f') +' </td> \n'
        html_code += '</tr>'

        entries.append(html_code)
    
    for i in range(len(out)):
        print(entries[rank2idx[i]])

In [24]:
get_entries('DRD3', 100)

---- DRD3 ------
<tr> 
  <td> 1 </td> 
  <td> SMILES-LSTM </td> 
  <td><a href="mailto:tfu42@gatech.edu">Tianfan Fu</a></td> 
  <td><a href="https://github.com/futianfan/guacamol_tdc"> GitHub</a>, <a href="https://pubs.acs.org/doi/10.1021/acscentsci.7b00512">Paper </a></td> 
  <td> 3,149,000 </td> 
  <td>-7.594 <span>&#177;</span> 0.182 </td> 
  <td>-10.033 <span>&#177;</span> 0.186 </td> 
  <td>-11.133 <span>&#177;</span> 0.634 </td> 
  <td>0.884 <span>&#177;</span> 0.002 </td> 
  <td>1.000 <span>&#177;</span> 0.000 </td> 
  <td>0.763 <span>&#177;</span> 0.019 </td> 
  <td>-1.100 <span>&#177;</span> 1.417 </td> 
  <td>5.219 <span>&#177;</span> 0.247 </td> 
</tr>
<tr> 
  <td> 2 </td> 
  <td> Graph-GA </td> 
  <td><a href="mailto:tfu42@gatech.edu">Tianfan Fu</a></td> 
  <td><a href="https://github.com/futianfan/guacamol_tdc"> GitHub</a>, <a href="https://pubs.rsc.org/en/content/articlelanding/2019/sc/c8sc05372c#!divAbstract">Paper </a></td> 
  <td> 0 </td> 
  <td>-7.222 <span>&#177;</sp